[package]
name = "tree_case1"
version = "0.1.0"
authors = ["fnlcon <fnlcon@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
regex = "1.5.4"
